fixed StackOverflowException in TemplateRegion #53
Haulmont/jmix-reports pull request #80
Opened 2021-03-30 14:18 UTC by KartonDCP

This problem occurs due to the `_jmixEntityEntry` field that appears in runtime in `TemplateTableDescription` instance because it annotated with `JmixEntity`. This metadata field should not be serialized. In this way `gson` should ignore any metadata-inserted fields.

2021-03-31 12:40 UTC, NikitaShchienko commented on reports-ui/src/main/java/io/jmix/reportsui/wizard/template/generators/TableGenerator.java
> +@Scope("prototype")
Replace with  BeanDefinition.SCOPE_PROTOTYPE

2021-03-31 12:41 UTC, NikitaShchienko approved these changes

2021-03-31 17:34 UTC, KartonDCP commented on reports-ui/src/main/java/io/jmix/reportsui/wizard/template/TemplateGeneratorImpl.java
> -@Scope("prototype")
also replaced with BeanDefinition.SCOPE_PROTOTYPE

2021-04-05 06:19 UTC, gorbunkov requested changes

2021-04-05 06:19 UTC, gorbunkov commented on reports/src/main/java/io/jmix/reports/app/StrategyGsonBuilder.java
> +        ignoreMetadata,
Enumeration values are usually written in uppercase with underscore, e.g. IGNORE_METADATA

2021-04-05 06:19 UTC, gorbunkov commented on reports/src/main/java/io/jmix/reports/app/StrategyGsonBuilder.java
> +        ignoreFields,
Why do we need this "ignoreFields" strategy? Why to serialize an entity with no fields? As I see this enum value is never used in the code.

2021-04-05 06:19 UTC, gorbunkov commented on reports/src/main/java/io/jmix/reports/app/StrategyGsonBuilder.java
> +        convertAll
convertAll is also never used. Why do we need it?

2021-04-05 06:19 UTC, gorbunkov commented on reports/src/main/java/io/jmix/reports/app/StrategyGsonBuilder.java
> +public class StrategyGsonBuilder {
A very common class name that doesn't explain what the class does. What strategy does it build? As I see, you use only ignoreMetadata serialization policy. Maybe it's worth thinking about removing the SerializationPolicy enum at all and rename the class into something like `MetadataIgnoringGsonBuilder`?

2021-04-07 18:39 UTC, gorbunkov approved these changes

2021-04-09 11:25 UTC, merged